version: '3'

services:
    db:
        image: postgres
    django:
        build:
            context: .
        command: ./wait-for-it.sh db:5432 -- pipenv run ./spacenews/manage.py runserver 0.0.0.0:8000
        expose:
            - "8000"
        volumes:
            - ./:/app
        depends_on:
            - db
    nginx:
        image: nginx:latest
        ports:
            - "8000:8000"
        volumes:
            - ./config/nginx/nginx:/etc/nginx/conf.d
        depends_on:
            - django
